.TH EZ 1 "April 27, 2014" "Mac OS X" "BSD General Commands Manual"

.SH NAME ez \- Awesome File Compression

.SH SYNOPSIS

ez [-vlh] 

ez [-cx] file ...

.SH DESCRIPTION

EZip uses Huffman Tree encoding to generate variable length codes, with the most frequent character having the shortest code and the least frequent character having the longest code.

.SH OPTIONS

\fB-v\fR \- Prints EZip version.

\fB-h\fR \- Shows this help page.

\fB-l\fR \- Shows the EZip License.

\fB-c\fR \- Compresses a file.

\fB-x\fR \- Extract a file.
